//------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------------------------------

namespace Weather.Members {
	using System;
	using App.Data;
	
	
	/// <summary>会员</summary>
	public partial class Member : App.Resources.Actor {
		
		private static App.Data.DataType _resourceType;
		

		partial void OnBeforeInitialize();

		partial void OnEndInitialize();

		
		static Member() {
			Weather.Members.Member._resourceType = ((App.Data.DataType)(App.Data.DataType.GetByFullName("Weather.Members.Member")));
		}
		
		/// <summary>真实姓名</summary>
		public new string Name {
			get {
				return ((string)(base.GetValue(7)));
			}
			set {
				base.SetValue(7, value);
			}
		}
		
		/// <summary>编号</summary>
		public new string Code {
			get {
				return ((string)(base.GetValue(8)));
			}
			set {
				base.SetValue(8, value);
			}
		}
		
		/// <summary>描述</summary>
		public new string Description {
			get {
				return ((string)(base.GetValue(9)));
			}
			set {
				base.SetValue(9, value);
			}
		}
		
		/// <summary>昵称</summary>
		public string NickName {
			get {
				return ((string)(base.GetValue(10)));
			}
			set {
				base.SetValue(10, value);
			}
		}
		
		/// <summary>手机号</summary>
		public string Mobile {
			get {
				return ((string)(base.GetValue(11)));
			}
			set {
				base.SetValue(11, value);
			}
		}
		
		/// <summary>邮箱</summary>
		public string Email {
			get {
				return ((string)(base.GetValue(12)));
			}
			set {
				base.SetValue(12, value);
			}
		}
		
		/// <summary>性别</summary>
		public int Sex {
			get {
				return ((int)(base.GetValue(13)));
			}
			set {
				base.SetValue(13, value);
			}
		}
		
		/// <summary>国家</summary>
		public string Country {
			get {
				return ((string)(base.GetValue(14)));
			}
			set {
				base.SetValue(14, value);
			}
		}
		
		/// <summary>省</summary>
		public string Province {
			get {
				return ((string)(base.GetValue(15)));
			}
			set {
				base.SetValue(15, value);
			}
		}
		
		/// <summary>城市</summary>
		public string City {
			get {
				return ((string)(base.GetValue(16)));
			}
			set {
				base.SetValue(16, value);
			}
		}
		
		/// <summary>会员头像</summary>
		public string Headimgurl {
			get {
				return ((string)(base.GetValue(17)));
			}
			set {
				base.SetValue(17, value);
			}
		}
		
		/// <summary>已兑换积分</summary>
		/// <remarks>消耗积分</remarks>
		public int PointsValueConsume {
			get {
				return ((int)(base.GetValue(18)));
			}
			set {
				base.SetValue(18, value);
			}
		}
		
		/// <summary>总积分</summary>
		/// <remarks>总积分</remarks>
		public int PointsValueTotal {
			get {
				return ((int)(base.GetValue(19)));
			}
			set {
				base.SetValue(19, value);
			}
		}
		
		/// <summary>微信OpenID</summary>
		/// <remarks>微信OpenID</remarks>
		public string WxOpenID {
			get {
				return ((string)(base.GetValue(20)));
			}
			set {
				base.SetValue(20, value);
			}
		}
		
		public new static App.Data.DataType GetSchema() {
			return Weather.Members.Member._resourceType;
		}
		
		public override App.Data.DataType GetDataType() {
			return Weather.Members.Member._resourceType;
		}
		
		protected override void Initialize() {
			this.OnBeforeInitialize();
			base.Initialize();
			base.propertyValues[5].Value = false;
			base.propertyValues[7].Value = "";
			base.propertyValues[10].Value = "";
			base.propertyValues[13].Value = 0;
			base.propertyValues[17].Value = "/Images/people.png";
			base.propertyValues[18].Value = 0;
			base.propertyValues[19].Value = 0;
			this.OnEndInitialize();
		}
	}
}
