//------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------------------------------

namespace Weather.Resources {
	using System;
	using App.Data;
	
	
	public partial class Resource1 : App.Data.Resource {
		
		private static App.Data.DataType _resourceType;
		

		partial void OnBeforeInitialize();

		partial void OnEndInitialize();

		
		static Resource1() {
			Weather.Resources.Resource1._resourceType = ((App.Data.DataType)(App.Data.DataType.GetByFullName("Weather.Resources.Resource1")));
		}
		
		public string Name {
			get {
				return ((string)(base.GetValue(6)));
			}
			set {
				base.SetValue(6, value);
			}
		}
		
		public string Code {
			get {
				return ((string)(base.GetValue(7)));
			}
			set {
				base.SetValue(7, value);
			}
		}
		
		public string Description {
			get {
				return ((string)(base.GetValue(8)));
			}
			set {
				base.SetValue(8, value);
			}
		}
		
		public static App.Data.DataType GetSchema() {
			return Weather.Resources.Resource1._resourceType;
		}
		
		public override App.Data.DataType GetDataType() {
			return Weather.Resources.Resource1._resourceType;
		}
		
		protected override void Initialize() {
			this.OnBeforeInitialize();
			base.Initialize();
			base.propertyValues[5].Value = false;
			this.OnEndInitialize();
		}
	}
}
