//------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------------------------------

namespace Weather.Resources {
	using System;
	using App.Data;
	
	
	/// <summary>奖励机制</summary>
	public partial class ScratchPrizeRule : App.Data.Resource {
		
		private static App.Data.DataType _resourceType;
		

		partial void OnBeforeInitialize();

		partial void OnEndInitialize();

		
		static ScratchPrizeRule() {
			Weather.Resources.ScratchPrizeRule._resourceType = ((App.Data.DataType)(App.Data.DataType.GetByFullName("Weather.Resources.ScratchPrizeRule")));
		}
		
		/// <summary>名称</summary>
		public string Name {
			get {
				return ((string)(base.GetValue(6)));
			}
			set {
				base.SetValue(6, value);
			}
		}
		
		/// <summary>奖励类型</summary>
		public Weather.Resources.PrizeType PrizeType {
			get {
				return ((Weather.Resources.PrizeType)(base.GetValue(7)));
			}
			set {
				base.SetValue(7, value);
			}
		}
		
		/// <summary>消耗积分</summary>
		public int ConsumePoints {
			get {
				return ((int)(base.GetValue(8)));
			}
			set {
				base.SetValue(8, value);
			}
		}
		
		/// <summary>概率百分比</summary>
		public int Chance {
			get {
				return ((int)(base.GetValue(9)));
			}
			set {
				base.SetValue(9, value);
			}
		}
		
		/// <summary>奖励值</summary>
		public decimal PrizeValue {
			get {
				return ((decimal)(base.GetValue(10)));
			}
			set {
				base.SetValue(10, value);
			}
		}
		
		/// <summary>描述</summary>
		public string Description {
			get {
				return ((string)(base.GetValue(11)));
			}
			set {
				base.SetValue(11, value);
			}
		}
		
		public static App.Data.DataType GetSchema() {
			return Weather.Resources.ScratchPrizeRule._resourceType;
		}
		
		public override App.Data.DataType GetDataType() {
			return Weather.Resources.ScratchPrizeRule._resourceType;
		}
		
		protected override void Initialize() {
			this.OnBeforeInitialize();
			base.Initialize();
			base.propertyValues[5].Value = false;
			base.propertyValues[8].Value = 0;
			base.propertyValues[9].Value = 0;
			base.propertyValues[10].Value = ((decimal)(0m));
			this.OnEndInitialize();
		}
	}
}


namespace Weather.Resources {
	using System;
	using App.Data;
	
	
	/// <summary>奖励类型</summary>
	public enum PrizeType {
		
		/// <summary>手机充值卡</summary>
		MobileReCharge = 0,
		
		/// <summary>积分</summary>
		PulsPoint = 1,
	}
}
